# Generated by Django 5.2.7 on 2025-12-10 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_first_name_customuser_last_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfirmCode',
        ),
    ]
